$p.display = function (defaultId) {
    var displays = {
        CanNotConnectCamera: 'Cannot connect to camera.',
        CanNotConnectCamera_zh: '无法连接至摄像机。',
        CanNotConnectCamera_ja: 'カメラに接続できません。',
        CanNotConnectCamera_de: 'Keine Verbindung zur Kamera m&#246;glich.',
        CanNotConnectCamera_ko: '카메라에 연결할 수 없습니다.',
        CanNotConnectCamera_es: 'No puede conectarse a la c&#225;mara.',
        CheckAll: 'Check all',
        CheckAll_zh: '选择全部',
        CheckAll_ja: '全て選択',
        CheckAll_de: 'Alle pr&#252;fen',
        CheckAll_ko: '모두 선택',
        CheckAll_es: 'Marcar todo',
        ConfirmCreateLink: 'Would you like to create a link?',
        ConfirmCreateLink_zh: '是否需要创建链接？',
        ConfirmCreateLink_ja: 'リンクを作成しますか？',
        ConfirmCreateLink_de: 'M&#246;chten Sie eine Verkn&#252;pfung erstellen?',
        ConfirmCreateLink_ko: '링크를 생성하시겠습니까?',
        ConfirmCreateLink_es: '&#191;Le gustar&#237;a crear un enlace?',
        ConfirmDelete: 'Are you sure you want to delete?',
        ConfirmDelete_zh: '是否确定删除？',
        ConfirmDelete_ja: '本当に削除してもよろしいですか？',
        ConfirmDelete_de: 'Tats&#228;chlich l&#246;schen?',
        ConfirmDelete_ko: '삭제하시겠습니까?',
        ConfirmDelete_es: '&#191;Est&#225; seguro de que quiere eliminar?',
        ConfirmPhysicalDelete: 'This operation cannot be undone. Are you sure you want to delete?',
        ConfirmPhysicalDelete_zh: '无法撤销此操作，是否确定删除？',
        ConfirmPhysicalDelete_ja: 'この操作を行うと元に戻すことはできません。本当に削除してもよろしいですか？',
        ConfirmPhysicalDelete_de: 'Dieser Vorgang kann nicht r&#252;ckg&#228;ngig gemacht werden. Tats&#228;chlich l&#246;schen?',
        ConfirmPhysicalDelete_ko: '이 작업은 실행 취소할 수 없습니다. 삭제하시겠습니까?',
        ConfirmPhysicalDelete_es: 'Esta operaci&#243;n no puede deshacerse. &#191;Est&#225; seguro de que quiere eliminar?',
        ConfirmRebuildSearchIndex: 'Would you like to rebuild the search index?',
        ConfirmRebuildSearchIndex_zh: '是否需要重建搜索索引？',
        ConfirmRebuildSearchIndex_ja: '検索インデックスを再構築しますか？',
        ConfirmRebuildSearchIndex_de: 'Soll der Suchindex neu erstellt werden?',
        ConfirmRebuildSearchIndex_ko: '검색 색인을 재구성하시겠습니까?',
        ConfirmRebuildSearchIndex_es: '&#191;Le gustar&#237;a volver a construir el &#237;ndice de b&#250;squeda?',
        ConfirmReload: 'Are you sure you want to reload this page?',
        ConfirmReload_ja: 'このページを離れようとしています。',
        ConfirmReset: 'Are you sure you want to reset?',
        ConfirmReset_zh: '是否确定重置？',
        ConfirmReset_ja: '本当にリセットしてもよろしいですか？',
        ConfirmReset_de: 'Tats&#228;chlich zur&#252;cksetzen?',
        ConfirmReset_ko: '재설정하시겠습니까?',
        ConfirmReset_es: '&#191;Est&#225; seguro de que quiere restablecer?',
        ConfirmRestore: 'Are you sure you want to restore?',
        ConfirmRestore_zh: '是否确定恢复？',
        ConfirmRestore_ja: '本当に復元してもよろしいですか？',
        ConfirmRestore_de: 'Tats&#228;chlich wiederherstellen?',
        ConfirmRestore_ko: '복원하시겠습니까?',
        ConfirmRestore_es: '&#191;Est&#225; seguro de quiere restaurar?',
        ConfirmSendMail: 'Are you sure you want to send the email?',
        ConfirmSendMail_zh: '是否确定发送邮件？',
        ConfirmSendMail_ja: 'メールを送信してもよろしいですか？',
        ConfirmSendMail_de: 'Soll die E-Mail tats&#228;chlich gesendet werden?',
        ConfirmSendMail_ko: '이메일을 전송하시겠습니까?',
        ConfirmSendMail_es: '&#191;Est&#225; seguro de que quiere enviar el correo electr&#243;nico?',
        ConfirmSeparate: 'Are you sure you want to divide?',
        ConfirmSeparate_zh: '是否确定划分？',
        ConfirmSeparate_ja: '分割してもよろしいですか？',
        ConfirmSeparate_de: 'Tats&#228;chlich aufteilen?',
        ConfirmSeparate_ko: '분할하시겠습니까?',
        ConfirmSeparate_es: '&#191;Est&#225; seguro de que quiere dividir?',
        ConfirmSwitchTenant: 'Are you sure you want to switch tenant?',
        ConfirmSwitchTenant_zh: '您确定要切换租户吗？',
        ConfirmSwitchTenant_ja: '本当にテナント切り替えますか？',
        ConfirmSwitchTenant_de: 'Sind Sie sicher, dass Sie den Mieter wechseln m&#246;chten?',
        ConfirmSwitchTenant_ko: '테넌트를 전환 하시겠습니까?',
        ConfirmSwitchTenant_es: '&#191;Est&#225;s seguro de que quieres cambiar de inquilino?',
        ConfirmSwitchUser: 'Are you sure you want to switch users?',
        ConfirmSwitchUser_zh: '是否确定切换用户？',
        ConfirmSwitchUser_ja: '本当にユーザを切り替えますか？',
        ConfirmSwitchUser_de: 'Soll der Benutzer tats&#228;chlich gewechselt werden?',
        ConfirmSwitchUser_ko: '사용자를 전환하시겠습니까?',
        ConfirmSwitchUser_es: '&#191;Est&#225; seguro de quiere cambiar los usuarios?',
        ConfirmSynchronize: 'Are you sure you want to synchronize the data?',
        ConfirmSynchronize_zh: '是否确定同步数据？',
        ConfirmSynchronize_ja: 'データを同期してもよろしいですか？',
        ConfirmSynchronize_de: 'Sollen die Daten tats&#228;chlich synchronisiert werden?',
        ConfirmSynchronize_ko: '데이터를 동기화하시겠습니까?',
        ConfirmSynchronize_es: '&#191;Est&#225; seguro de que quiere sincronizar los datos?',
        ConfirmUnload: 'Are you sure you want to leave this page? Changes you made may not be saved.',
        ConfirmUnload_zh: '是否确定离开此页面？离开后可能无法保存此前的变更。',
        ConfirmUnload_ja: 'このページを離れますか? 行った変更が保存されない可能性があります。',
        ConfirmUnload_de: 'M&#246;chten Sie diese Seite tats&#228;chlich verlassen? Die von Ihnen durchgef&#252;hrten &#196;nderungen werden m&#246;glicherweise nicht gespeichert.',
        ConfirmUnload_ko: '이 페이지에서 나가시겠습니까? 변경사항이 저장되지 않을 수 있습니다.',
        ConfirmUnload_es: '&#191;Est&#225; seguro de que quiere salir de este sitio? Es posible que no se guarden los cambios realizados.',
        ConfirmUnlockRecord: 'Are you sure you want to unlock this record?',
        ConfirmUnlockRecord_zh: '您确定要解锁此记录吗？',
        ConfirmUnlockRecord_ja: 'レコードのロックを解除してもよろしいですか？',
        ConfirmUnlockRecord_de: 'M&#246;chten Sie diesen Datensatz wirklich entsperren?',
        ConfirmUnlockRecord_ko: '이 레코드를 잠금 해제 하시겠습니까?',
        ConfirmUnlockRecord_es: '&#191;Est&#225;s seguro de que quieres desbloquear este registro?',
        DirectUrlCopied: 'Copied to clipboard',
        DirectUrlCopied_zh: '复制到剪贴板',
        DirectUrlCopied_ja: 'クリップボードにコピーしました',
        DirectUrlCopied_de: 'In die Zwischenablage kopiert',
        DirectUrlCopied_ko: '클립보드로 복사됨',
        DirectUrlCopied_es: 'Copiado al portapapeles',
        IncludeData: 'Include Data',
        IncludeData_zh: '包含数据',
        IncludeData_ja: 'データを含める',
        IncludeData_de: 'Daten einschlie&#223;en',
        IncludeData_ko: '데이터 포함',
        IncludeData_es: 'Incluir datos',
        Manager: 'Manager',
        Manager_zh: '经理',
        Manager_ja: '管理者',
        Manager_de: 'Manager',
        Manager_ko: '관리자',
        Manager_es: 'Gestor',
        OrderAsc: 'Ascendant',
        OrderAsc_zh: '上升',
        OrderAsc_ja: '昇順',
        OrderAsc_de: 'Aufsteigend',
        OrderAsc_ko: '오름차순',
        OrderAsc_es: 'Ascendente',
        OrderDesc: 'Descendant',
        OrderDesc_zh: '下降',
        OrderDesc_ja: '降順',
        OrderDesc_de: 'Absteigend',
        OrderDesc_ko: '내림차순',
        OrderDesc_es: 'Descendente',
        OrderRelease: 'Release',
        OrderRelease_zh: '释放',
        OrderRelease_ja: '解除',
        OrderRelease_de: 'Freigabe',
        OrderRelease_ko: '릴리즈',
        OrderRelease_es: 'Liberar',
        ResetOrder: 'Reset order',
        ResetOrder_zh: '重置顺序',
        ResetOrder_ja: 'リセット',
        ResetOrder_de: 'Reihenfolge zur&#252;cksetzen',
        ResetOrder_ko: '순서 재설정',
        ResetOrder_es: 'Restablecer orden',
        UncheckAll: 'Uncheck all',
        UncheckAll_zh: '取消全选',
        UncheckAll_ja: '全て解除',
        UncheckAll_de: 'Alle Markierungen aufheben',
        UncheckAll_ko: '모두 선택 취소',
        UncheckAll_es: 'Desmarcar todo',
        ValidateDate: 'Invalid date or time.',
        ValidateDate_zh: '日期或时间无效。',
        ValidateDate_ja: '日付または時刻が不正です。',
        ValidateDate_de: 'Datum oder Uhrzeit ung&#252;ltig.',
        ValidateDate_ko: '유효하지 않은 날짜 또는 시간입니다.',
        ValidateDate_es: 'Fecha u hora no v&#225;lida.',
        ValidateEmail: 'Invalid email address.',
        ValidateEmail_zh: '电子邮箱地址无效。',
        ValidateEmail_ja: 'メールアドレスの形式が不正です。',
        ValidateEmail_de: 'E-Mail-Adresse ung&#252;ltig.',
        ValidateEmail_ko: '유효하지 않은 이메일 주소입니다.',
        ValidateEmail_es: 'Direcci&#243;n de correo electr&#243;nica no v&#225;lida.',
        ValidateEqualTo: 'The text entered does not match.',
        ValidateEqualTo_zh: '输入的文本不匹配。',
        ValidateEqualTo_ja: '入力した文字列が一致しません。',
        ValidateEqualTo_de: 'Der eingegebene Text stimmt nicht &#252;berein.',
        ValidateEqualTo_ko: '입력한 텍스트가 일치하지 않습니다.',
        ValidateEqualTo_es: 'El texto introducido no coincide.',
        ValidateMaxLength: 'The text entered is too long.',
        ValidateMaxLength_zh: '输入的文本过长。',
        ValidateMaxLength_ja: '入力した文字が長すぎます。',
        ValidateMaxLength_de: 'Der eingegebene Text ist zu lang.',
        ValidateMaxLength_ko: '입력한 텍스트가 너무 깁니다.',
        ValidateMaxLength_es: 'El texto introducido es demasiado largo.',
        ValidateMaxNumber: 'The number entered is too large.',
        ValidateMaxNumber_zh: '输入的数字过大。',
        ValidateMaxNumber_ja: '入力された数字が大きすぎます。',
        ValidateMaxNumber_de: 'Die eingegebene Zahl ist zu gro&#223;.',
        ValidateMaxNumber_ko: '입력한 숫자가 너무 큽니다.',
        ValidateMaxNumber_es: 'El n&#250;mero introducido es demasiado largo.',
        ValidateMinNumber: 'The number entered is too small.',
        ValidateMinNumber_zh: '输入的数字过小。',
        ValidateMinNumber_ja: '入力された数字が小さすぎます。',
        ValidateMinNumber_de: 'Die eingegebene Zahl ist zu klein.',
        ValidateMinNumber_ko: '입력한 숫자가 너무 작습니다.',
        ValidateMinNumber_es: 'El n&#250;mero introducido es demasiado peque&#241;o.',
        ValidateNumber: 'Only numeric value can be entered.',
        ValidateNumber_zh: '只能输入数字。',
        ValidateNumber_ja: '数値以外入力不可です。',
        ValidateNumber_de: 'Es k&#246;nnen nur numerische Werte eingegeben werden.',
        ValidateNumber_ko: '수치값만 입력할 수 있습니다.',
        ValidateNumber_es: 'Solo pueden introducirse valores num&#233;ricos.',
        ValidateRequired: 'This is a required field.',
        ValidateRequired_zh: '必填字段。',
        ValidateRequired_ja: '入力必須項目です。',
        ValidateRequired_de: 'Dieses Feld muss ausgef&#252;llt werden.',
        ValidateRequired_ko: '필수 입력 필드입니다.',
        ValidateRequired_es: 'Este es un campo obligatorio.',
        ValidationError: 'The data entered is incorrect.',
        ValidationError_zh: '输入的数据错误。',
        ValidationError_ja: '入力された内容に誤りがあります。',
        ValidationError_de: 'Die eingegebenen Daten sind falsch.',
        ValidationError_ko: '입력한 데이터가 올바르지 않습니다.',
        ValidationError_es: 'El dato introducido es incorrecto.'
    };
    var localId = defaultId + '_' + $('#Language').val();
    if (displays[localId]) {
        return displays[localId];
    } else if (displays[defaultId]) {
        return displays[defaultId];
    } else {
        return defaultId;
    }
}
