using Implem.Pleasanter.Libraries.Converts;
using Implem.Pleasanter.Libraries.DataTypes;
using Implem.Pleasanter.Libraries.Server;
using Implem.Pleasanter.Libraries.Settings;
using System;
using System.Collections.Generic;
namespace Implem.Pleasanter.Models
{
    public class IssueSubset
    {
        public long SiteId;
        public Time UpdatedTime;
        public long IssueId;
        public Title Title;
        public string Body;
        public DateTime StartTime;
        public CompletionTime CompletionTime;
        public WorkValue WorkValue;
        public ProgressRate ProgressRate;
        public Status Status;
        public User Manager;
        public User Owner;
        public string ClassA;
        public string ClassB;
        public string ClassC;
        public string ClassD;
        public string ClassE;
        public string ClassF;
        public string ClassG;
        public string ClassH;
        public string ClassI;
        public string ClassJ;
        public string ClassK;
        public string ClassL;
        public string ClassM;
        public string ClassN;
        public string ClassO;
        public string ClassP;
        public string ClassQ;
        public string ClassR;
        public string ClassS;
        public string ClassT;
        public string ClassU;
        public string ClassV;
        public string ClassW;
        public string ClassX;
        public string ClassY;
        public string ClassZ;
        public decimal NumA;
        public decimal NumB;
        public decimal NumC;
        public decimal NumD;
        public decimal NumE;
        public decimal NumF;
        public decimal NumG;
        public decimal NumH;
        public decimal NumI;
        public decimal NumJ;
        public decimal NumK;
        public decimal NumL;
        public decimal NumM;
        public decimal NumN;
        public decimal NumO;
        public decimal NumP;
        public decimal NumQ;
        public decimal NumR;
        public decimal NumS;
        public decimal NumT;
        public decimal NumU;
        public decimal NumV;
        public decimal NumW;
        public decimal NumX;
        public decimal NumY;
        public decimal NumZ;
        public DateTime DateA;
        public DateTime DateB;
        public DateTime DateC;
        public DateTime DateD;
        public DateTime DateE;
        public DateTime DateF;
        public DateTime DateG;
        public DateTime DateH;
        public DateTime DateI;
        public DateTime DateJ;
        public DateTime DateK;
        public DateTime DateL;
        public DateTime DateM;
        public DateTime DateN;
        public DateTime DateO;
        public DateTime DateP;
        public DateTime DateQ;
        public DateTime DateR;
        public DateTime DateS;
        public DateTime DateT;
        public DateTime DateU;
        public DateTime DateV;
        public DateTime DateW;
        public DateTime DateX;
        public DateTime DateY;
        public DateTime DateZ;
        public string DescriptionA;
        public string DescriptionB;
        public string DescriptionC;
        public string DescriptionD;
        public string DescriptionE;
        public string DescriptionF;
        public string DescriptionG;
        public string DescriptionH;
        public string DescriptionI;
        public string DescriptionJ;
        public string DescriptionK;
        public string DescriptionL;
        public string DescriptionM;
        public string DescriptionN;
        public string DescriptionO;
        public string DescriptionP;
        public string DescriptionQ;
        public string DescriptionR;
        public string DescriptionS;
        public string DescriptionT;
        public string DescriptionU;
        public string DescriptionV;
        public string DescriptionW;
        public string DescriptionX;
        public string DescriptionY;
        public string DescriptionZ;
        public Comments Comments;
        public User Creator;
        public User Updator;
        public Time CreatedTime;

        public IssueSubset()
        {
        }

        public IssueSubset(IssueModel issueModel, SiteSettings siteSettings)
        {
            SiteId = issueModel.SiteId;
            UpdatedTime = issueModel.UpdatedTime;
            IssueId = issueModel.IssueId;
            Title = issueModel.Title;
            Body = issueModel.Body;
            StartTime = issueModel.StartTime;
            CompletionTime = issueModel.CompletionTime;
            WorkValue = issueModel.WorkValue;
            ProgressRate = issueModel.ProgressRate;
            Status = issueModel.Status;
            Manager = issueModel.Manager;
            Owner = issueModel.Owner;
            ClassA = issueModel.ClassA;
            ClassB = issueModel.ClassB;
            ClassC = issueModel.ClassC;
            ClassD = issueModel.ClassD;
            ClassE = issueModel.ClassE;
            ClassF = issueModel.ClassF;
            ClassG = issueModel.ClassG;
            ClassH = issueModel.ClassH;
            ClassI = issueModel.ClassI;
            ClassJ = issueModel.ClassJ;
            ClassK = issueModel.ClassK;
            ClassL = issueModel.ClassL;
            ClassM = issueModel.ClassM;
            ClassN = issueModel.ClassN;
            ClassO = issueModel.ClassO;
            ClassP = issueModel.ClassP;
            ClassQ = issueModel.ClassQ;
            ClassR = issueModel.ClassR;
            ClassS = issueModel.ClassS;
            ClassT = issueModel.ClassT;
            ClassU = issueModel.ClassU;
            ClassV = issueModel.ClassV;
            ClassW = issueModel.ClassW;
            ClassX = issueModel.ClassX;
            ClassY = issueModel.ClassY;
            ClassZ = issueModel.ClassZ;
            NumA = issueModel.NumA;
            NumB = issueModel.NumB;
            NumC = issueModel.NumC;
            NumD = issueModel.NumD;
            NumE = issueModel.NumE;
            NumF = issueModel.NumF;
            NumG = issueModel.NumG;
            NumH = issueModel.NumH;
            NumI = issueModel.NumI;
            NumJ = issueModel.NumJ;
            NumK = issueModel.NumK;
            NumL = issueModel.NumL;
            NumM = issueModel.NumM;
            NumN = issueModel.NumN;
            NumO = issueModel.NumO;
            NumP = issueModel.NumP;
            NumQ = issueModel.NumQ;
            NumR = issueModel.NumR;
            NumS = issueModel.NumS;
            NumT = issueModel.NumT;
            NumU = issueModel.NumU;
            NumV = issueModel.NumV;
            NumW = issueModel.NumW;
            NumX = issueModel.NumX;
            NumY = issueModel.NumY;
            NumZ = issueModel.NumZ;
            DateA = issueModel.DateA;
            DateB = issueModel.DateB;
            DateC = issueModel.DateC;
            DateD = issueModel.DateD;
            DateE = issueModel.DateE;
            DateF = issueModel.DateF;
            DateG = issueModel.DateG;
            DateH = issueModel.DateH;
            DateI = issueModel.DateI;
            DateJ = issueModel.DateJ;
            DateK = issueModel.DateK;
            DateL = issueModel.DateL;
            DateM = issueModel.DateM;
            DateN = issueModel.DateN;
            DateO = issueModel.DateO;
            DateP = issueModel.DateP;
            DateQ = issueModel.DateQ;
            DateR = issueModel.DateR;
            DateS = issueModel.DateS;
            DateT = issueModel.DateT;
            DateU = issueModel.DateU;
            DateV = issueModel.DateV;
            DateW = issueModel.DateW;
            DateX = issueModel.DateX;
            DateY = issueModel.DateY;
            DateZ = issueModel.DateZ;
            DescriptionA = issueModel.DescriptionA;
            DescriptionB = issueModel.DescriptionB;
            DescriptionC = issueModel.DescriptionC;
            DescriptionD = issueModel.DescriptionD;
            DescriptionE = issueModel.DescriptionE;
            DescriptionF = issueModel.DescriptionF;
            DescriptionG = issueModel.DescriptionG;
            DescriptionH = issueModel.DescriptionH;
            DescriptionI = issueModel.DescriptionI;
            DescriptionJ = issueModel.DescriptionJ;
            DescriptionK = issueModel.DescriptionK;
            DescriptionL = issueModel.DescriptionL;
            DescriptionM = issueModel.DescriptionM;
            DescriptionN = issueModel.DescriptionN;
            DescriptionO = issueModel.DescriptionO;
            DescriptionP = issueModel.DescriptionP;
            DescriptionQ = issueModel.DescriptionQ;
            DescriptionR = issueModel.DescriptionR;
            DescriptionS = issueModel.DescriptionS;
            DescriptionT = issueModel.DescriptionT;
            DescriptionU = issueModel.DescriptionU;
            DescriptionV = issueModel.DescriptionV;
            DescriptionW = issueModel.DescriptionW;
            DescriptionX = issueModel.DescriptionX;
            DescriptionY = issueModel.DescriptionY;
            DescriptionZ = issueModel.DescriptionZ;
            Comments = issueModel.Comments;
            Creator = issueModel.Creator;
            Updator = issueModel.Updator;
            CreatedTime = issueModel.CreatedTime;
        }

        public Dictionary<string, int> SearchIndexCollection()
        {
            var searchIndexHash = new Dictionary<string, int>();
            SiteInfo.SiteMenu.Breadcrumb(SiteId).SearchIndexes(searchIndexHash, 100);
            SiteId.SearchIndexes(searchIndexHash, 200);
            UpdatedTime.SearchIndexes(searchIndexHash, 200);
            IssueId.SearchIndexes(searchIndexHash, 1);
            Title.SearchIndexes(searchIndexHash, 4);
            Body.SearchIndexes(searchIndexHash, 200);
            StartTime.SearchIndexes(searchIndexHash, 200);
            CompletionTime.SearchIndexes(searchIndexHash, 200);
            WorkValue.SearchIndexes(searchIndexHash, 200);
            ProgressRate.SearchIndexes(searchIndexHash, 200);
            Status.SearchIndexes(searchIndexHash, 200);
            Manager.SearchIndexes(searchIndexHash, 100);
            Owner.SearchIndexes(searchIndexHash, 100);
            ClassA.SearchIndexes(searchIndexHash, 200);
            ClassB.SearchIndexes(searchIndexHash, 200);
            ClassC.SearchIndexes(searchIndexHash, 200);
            ClassD.SearchIndexes(searchIndexHash, 200);
            ClassE.SearchIndexes(searchIndexHash, 200);
            ClassF.SearchIndexes(searchIndexHash, 200);
            ClassG.SearchIndexes(searchIndexHash, 200);
            ClassH.SearchIndexes(searchIndexHash, 200);
            ClassI.SearchIndexes(searchIndexHash, 200);
            ClassJ.SearchIndexes(searchIndexHash, 200);
            ClassK.SearchIndexes(searchIndexHash, 200);
            ClassL.SearchIndexes(searchIndexHash, 200);
            ClassM.SearchIndexes(searchIndexHash, 200);
            ClassN.SearchIndexes(searchIndexHash, 200);
            ClassO.SearchIndexes(searchIndexHash, 200);
            ClassP.SearchIndexes(searchIndexHash, 200);
            ClassQ.SearchIndexes(searchIndexHash, 200);
            ClassR.SearchIndexes(searchIndexHash, 200);
            ClassS.SearchIndexes(searchIndexHash, 200);
            ClassT.SearchIndexes(searchIndexHash, 200);
            ClassU.SearchIndexes(searchIndexHash, 200);
            ClassV.SearchIndexes(searchIndexHash, 200);
            ClassW.SearchIndexes(searchIndexHash, 200);
            ClassX.SearchIndexes(searchIndexHash, 200);
            ClassY.SearchIndexes(searchIndexHash, 200);
            ClassZ.SearchIndexes(searchIndexHash, 200);
            NumA.SearchIndexes(searchIndexHash, 200);
            NumB.SearchIndexes(searchIndexHash, 200);
            NumC.SearchIndexes(searchIndexHash, 200);
            NumD.SearchIndexes(searchIndexHash, 200);
            NumE.SearchIndexes(searchIndexHash, 200);
            NumF.SearchIndexes(searchIndexHash, 200);
            NumG.SearchIndexes(searchIndexHash, 200);
            NumH.SearchIndexes(searchIndexHash, 200);
            NumI.SearchIndexes(searchIndexHash, 200);
            NumJ.SearchIndexes(searchIndexHash, 200);
            NumK.SearchIndexes(searchIndexHash, 200);
            NumL.SearchIndexes(searchIndexHash, 200);
            NumM.SearchIndexes(searchIndexHash, 200);
            NumN.SearchIndexes(searchIndexHash, 200);
            NumO.SearchIndexes(searchIndexHash, 200);
            NumP.SearchIndexes(searchIndexHash, 200);
            NumQ.SearchIndexes(searchIndexHash, 200);
            NumR.SearchIndexes(searchIndexHash, 200);
            NumS.SearchIndexes(searchIndexHash, 200);
            NumT.SearchIndexes(searchIndexHash, 200);
            NumU.SearchIndexes(searchIndexHash, 200);
            NumV.SearchIndexes(searchIndexHash, 200);
            NumW.SearchIndexes(searchIndexHash, 200);
            NumX.SearchIndexes(searchIndexHash, 200);
            NumY.SearchIndexes(searchIndexHash, 200);
            NumZ.SearchIndexes(searchIndexHash, 200);
            DateA.SearchIndexes(searchIndexHash, 200);
            DateB.SearchIndexes(searchIndexHash, 200);
            DateC.SearchIndexes(searchIndexHash, 200);
            DateD.SearchIndexes(searchIndexHash, 200);
            DateE.SearchIndexes(searchIndexHash, 200);
            DateF.SearchIndexes(searchIndexHash, 200);
            DateG.SearchIndexes(searchIndexHash, 200);
            DateH.SearchIndexes(searchIndexHash, 200);
            DateI.SearchIndexes(searchIndexHash, 200);
            DateJ.SearchIndexes(searchIndexHash, 200);
            DateK.SearchIndexes(searchIndexHash, 200);
            DateL.SearchIndexes(searchIndexHash, 200);
            DateM.SearchIndexes(searchIndexHash, 200);
            DateN.SearchIndexes(searchIndexHash, 200);
            DateO.SearchIndexes(searchIndexHash, 200);
            DateP.SearchIndexes(searchIndexHash, 200);
            DateQ.SearchIndexes(searchIndexHash, 200);
            DateR.SearchIndexes(searchIndexHash, 200);
            DateS.SearchIndexes(searchIndexHash, 200);
            DateT.SearchIndexes(searchIndexHash, 200);
            DateU.SearchIndexes(searchIndexHash, 200);
            DateV.SearchIndexes(searchIndexHash, 200);
            DateW.SearchIndexes(searchIndexHash, 200);
            DateX.SearchIndexes(searchIndexHash, 200);
            DateY.SearchIndexes(searchIndexHash, 200);
            DateZ.SearchIndexes(searchIndexHash, 200);
            DescriptionA.SearchIndexes(searchIndexHash, 200);
            DescriptionB.SearchIndexes(searchIndexHash, 200);
            DescriptionC.SearchIndexes(searchIndexHash, 200);
            DescriptionD.SearchIndexes(searchIndexHash, 200);
            DescriptionE.SearchIndexes(searchIndexHash, 200);
            DescriptionF.SearchIndexes(searchIndexHash, 200);
            DescriptionG.SearchIndexes(searchIndexHash, 200);
            DescriptionH.SearchIndexes(searchIndexHash, 200);
            DescriptionI.SearchIndexes(searchIndexHash, 200);
            DescriptionJ.SearchIndexes(searchIndexHash, 200);
            DescriptionK.SearchIndexes(searchIndexHash, 200);
            DescriptionL.SearchIndexes(searchIndexHash, 200);
            DescriptionM.SearchIndexes(searchIndexHash, 200);
            DescriptionN.SearchIndexes(searchIndexHash, 200);
            DescriptionO.SearchIndexes(searchIndexHash, 200);
            DescriptionP.SearchIndexes(searchIndexHash, 200);
            DescriptionQ.SearchIndexes(searchIndexHash, 200);
            DescriptionR.SearchIndexes(searchIndexHash, 200);
            DescriptionS.SearchIndexes(searchIndexHash, 200);
            DescriptionT.SearchIndexes(searchIndexHash, 200);
            DescriptionU.SearchIndexes(searchIndexHash, 200);
            DescriptionV.SearchIndexes(searchIndexHash, 200);
            DescriptionW.SearchIndexes(searchIndexHash, 200);
            DescriptionX.SearchIndexes(searchIndexHash, 200);
            DescriptionY.SearchIndexes(searchIndexHash, 200);
            DescriptionZ.SearchIndexes(searchIndexHash, 200);
            Comments.SearchIndexes(searchIndexHash, 200);
            Creator.SearchIndexes(searchIndexHash, 100);
            Updator.SearchIndexes(searchIndexHash, 100);
            CreatedTime.SearchIndexes(searchIndexHash, 200);
            SearchIndexExtensions.OutgoingMailsSearchIndexes(searchIndexHash, "Issues", IssueId);
            return searchIndexHash;
        }
    }
}
