# bug_report.yml
name: バグ報告
description: 不具合報告はこちら
labels: ["bug"]
title: 'Bug: '
body:
  - type: textarea
    attributes:
      label: 概要
      description: 不具合の概要を記載してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 発生条件
      description: 問題が発生する条件や状況を記載してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 期待する結果
    validations:
      required: true
  - type: textarea
    attributes:
      label: 現状の結果
    validations:
      required: true
  - type: textarea
    id: process
    attributes:
      label: 再現手順
      description: 不具合を再現させる手順を記載してください
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: バージョン情報
      description: |
        事象を確認したプリザンターのバージョンを記載してください
        例: 
        1.4.10.3
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: 再現環境
      description: |
        データベースやサーバー構成など、事象を確認した環境を記載してください
        例：
        Windows Server + SQLServer
        ubuntu + PostgreSQL
  - type: textarea
    id: supplement
    attributes:
      label: 追加情報
      description: |
        追加情報があれば記載してください。
        事象の再現するサイトパッケージがあればこちらに添付してください。
