blank_issues_enabled: false
contact_links:
  - name: 上記以外の問題に関するお問い合わせ
    url: https://pleasanter.org/contact
    about: |
      以下のような内容についてはこちらのお問い合わせ窓口よりご連絡ください。
      - 製品・サービスの利用方法に関するご質問
      - 個別の環境やケースに依存する問題のご相談
      - サポート対応を必要とするお問い合わせ
      
      ⚠GitHub Issues は、製品の改善に関する技術的な報告・提案を目的としています。
      ご理解とご協力のほど、よろしくお願いいたします。
