blank_issues_enabled: false
contact_links:
  - name: バグ報告、機能リクエスト以外のお問い合わせ
    url: https://pleasanter.org/contact
    about: 次のような内容についてはこちらのお問い合わせ窓口よりご連絡ください。●「製品・サービスの利用方法に関するご質問」　●「個別の環境やケースに依存する問題のご相談」 ●「サポート対応を必要とするお問い合わせ」
