name: build and xUnit test for MySQL
on:
  schedule:
    - cron: '0 13 * * *'   # UTC (= 22:00 JST)
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:
jobs:
    run_xunit_test:
        name: Run xUnit test for MySQL
        if: github.repository == 'Implem/Implem.Pleasanter.NetCore.Private' && github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        env:
            Implem_Pleasanter_Rds_MySQL_SaConnectionString: ${{ secrets.PLEASANTER_MYSQL_RDS_SA_CONN }}
            Implem_Pleasanter_Rds_MySQL_OwnerConnectionString: ${{ secrets.PLEASANTER_MYSQL_RDS_OWNER_CONN }}
            Implem_Pleasanter_Rds_MySQL_UserConnectionString: ${{ secrets.PLEASANTER_MYSQL_RDS_USER_CONN }}
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            DOCKER_BUILDKIT: 1
            COMPOSE_DOCKER_CLI_BUILD: true
        steps:
            - uses: actions/checkout@v4
            - name: build on docker compose for MySQL
              working-directory: ./
              run: docker compose -f docker-compose-for-my-sql.yml build Implem.CodeDefiner Implem.PleasanterTest
            - name: run Implem.CodeDefiner on docker compose for MySQL
              run: docker compose -f docker-compose-for-my-sql.yml run --rm Implem.CodeDefiner _rds /y
              working-directory: ./
            - name: execute query create user for MySQL
              working-directory: ./
              run: |
                  mysql -h db --port 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }}
                  -e $"create user 'Implem.Pleasanter_Owner'@'%' identified by 'dummy';
                       grant all on `Implem.Pleasanter`.* to 'Implem.Pleasanter_Owner'@'%' with grant option;
                       create user 'Implem.Pleasanter_User'@'%' identified by 'dummy';
                       grant select, insert, update, delete, create routine, alter routine on `Implem.Pleasanter`.* to 'Implem.Pleasanter_User'@'%';"
            - name: run Implem.PleasanterTest on docker compose for MySQL
              run: docker compose -f docker-compose-for-my-sql.yml run --rm Implem.PleasanterTest
              working-directory: ./
            - name: clean up on docker compose for MySQL
              run: docker compose -f docker-compose-for-my-sql.yml down
              working-directory: ./
